// user's consts

export const FETCH_SESSION_REQUEST = 'FETCH_SESSION_REQUEST';
export const FETCH_SESSION_SUCCESS = 'FETCH_SESSION_SUCCESS';
export const FETCH_SESSION_FAILURE = 'FETCH_SESSION_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST";
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE";

export const VERIFY_OTP = 'VERIFY_OTP';
export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

// visitors consts
export const FETCH_VISITORS_REQUEST = 'FETCH_VISITORS_REQUEST';
export const FETCH_VISITORS_SUCCESS = 'FETCH_VISITORS_SUCCESS';
export const FETCH_VISITORS_FAILURE = 'FETCH_VISITORS_FAILURE';

export const ADD_VISITOR_REQUEST = 'ADD_VISITOR_REQUEST';
export const ADD_VISITOR_SUCCESS = 'ADD_VISITOR_SUCCESS';
export const ADD_VISITOR_FAILURE = 'ADD_VISITOR_FAILURE';

export const UPDATE_VISITOR_REQUEST = 'UPDATE_VISITOR_REQUEST';
export const UPDATE_VISITOR_SUCCESS = 'UPDATE_VISITOR_SUCCESS';
export const UPDATE_VISITOR_FAILURE = 'UPDATE_VISITOR_FAILURE';

export const DELETE_VISITOR_REQUEST = 'DELETE_VISITOR_REQUEST';
export const DELETE_VISITOR_SUCCESS = 'DELETE_VISITOR_SUCCESS';
export const DELETE_VISITOR_FAILURE = 'DELETE_VISITOR_FAILURE';

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";